### ISSUE TITLE
Checklist for official git repo migration

### ISSUE THREAD

**Issue by dequis** [dequis/bitlbee#66]
- [x] Rebase branches and merge all the pending patches
  - [x] `for-wilmer-19-jan`
  - [x] `wip/md5`
  - [x] `feat/hip-cat` (welp)
  - [x] `patch/twitter-filter` (jgeboski)
  - [x] `patch/mode-special` (jgeboski)
  - [x] `wip/jabber-subprotocols`
  - [x] `patch/headers`
  - [x] `patch/use-dev-urandom-properly`
  - [x] `flexo/python`
  - [x] `WPettersson:twitter_format_strings`
  - [x] `WPettersson:rawreply`
  - [x] `WPettersson:threads` (he will take care)
  - [x] `patch/carbons`
- [x] Reindent (5983eca9ac1187eb1407eece7d7ad72ef5e091b0)
- [x] Some nightly build system
- [x] Poke everyone who starred or watched this repo to move over

**Comment by dequis** [comment]
Sorry for the mass-ping everyone, please un-watch or un-star this repo! Trying to bury it without breaking old links to it.

The new repo (if you care) is: https://github.com/bitlbee/bitlbee/

~~removed~~

**Comment by dequis** [comment]
Second attempt!

> Sorry for the mass-ping everyone, please un-watch or un-star this repo! Trying to bury it without breaking old links to it.
> 
> The new repo (if you care) is: https://github.com/bitlbee/bitlbee/

~~removed~~

**Comment by andresilva** [comment]
Done, cheers!

**Comment by dequis** [comment]
@andrebeat still see you here though https://github.com/dequis/bitlbee-old/stargazers

**EDIT**: locking comments since apparently people who already unstarred the repo get pinged anyway, sorry for that!
